FROM flameaxe/diploma:latest

ENV ASDF_DIR="/root/.asdf"
ENV PATH="${PATH}:/root/.asdf/shims:/root/.asdf/bin:/root/.asdf/installs/ruby/2.5.1/bin:/root/.asdf/installs/nodejs/v12.22.12/bin:root/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/"

WORKDIR /diploma
EXPOSE 3000
STOPSIGNAL SIGTERM
CMD bundle exec rails s -b 0.0.0.0 -e production

