services:
  db:
    image: mysql:8.0.30
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_dev:/var/lib/mysql
      - db_mysqld_dev:/var/run/mysqld
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cardwalls_development
      MYSQL_USER: flameaxe
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: rails s -b 0.0.0.0
    volumes:
      - ".:/diploma"
      - "/diploma/public"
      - "/diploma/node_modules"
    ports:
      - "3001:3000"
    environment:
      DB_USER: flameaxe
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: cardwalls_development
      SENDGRID_API_KEY: "${SENDGRID_API_KEY}"
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 'true'
    depends_on:
      - db
    links:
      - db
  asset_pipeline:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/webpack-dev-server
    volumes:
      - ".:/diploma"
      - "/diploma/public"
      - "/diploma/node_modules"
    ports:
      - "3035:3035"
    depends_on:
      - db
    links:
      - db

volumes:
  db_dev:
  db_mysqld_dev:

