name: Run tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.30
        env:
          MYSQL_DATABASE: cardwalls_test
          MYSQL_USER: flameaxe
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: 2.5.1
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Run tests
        env:
          RAILS_ENV: test
          DB_USER: flameaxe
          DB_PASSWORD: password
          DB_HOST: 127.0.0.1
          DB_NAME: cardwalls_test
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:migrate
          bundle exec rspec